### ISSUE TITLE
Microbenchmarks 

### ISSUE THREAD

**Issue by navdeepkk** [PrincetonUniversity/faas-profiler#1]
Hi, I was just reading your paper and it said you have used 28 micribenchmarks. I was just tring to do what is done in the paper but was not able to get the microbenchmarks. Can you please provide the micro benchmarks you have written.

**Comment by engshahrad** [comment]
Thanks for your interest. As listed in the paper, those benchmarks are from the Python Performance Benchmark Suite (Reference #33 of the paper). Here is the link to it:
https://pyperformance.readthedocs.io 
(We will make this clear in the README file too)

The benchmarks included in the repo are those that we gathered individually and developed ourselves. Here is the link for those: https://github.com/PrincetonUniversity/faas-profiler/tree/master/functions

**Comment by navdeepkk** [comment]
Thanks a lot sir.
I am running open whisk using vagrant. I am not able to get FaaS profiler up and running. I have changed APIHOST and APIKEY in workload invoker file. However i do not know further Configurations to be done. Trivial it may sound, but can you please guide me through the process.I will be really thankful to you.

**Comment by navdeepkk** [comment]
Also is it using REST Api or using the wsk CLI.

**Comment by engshahrad** [comment]
Created new issues based on your new questions and since the original question is answered I am closing this issue.
