### ISSUE TITLE
Error with profilling

### ISSUE THREAD

**Issue by Vasilis99** [PrincetonUniversity/faas-profiler#12]
{
    "test_name": "example_test",
    "test_duration_in_seconds": 15,
    "random_seed": 100,
    "blocking_cli": true,
    "instances":{
        "instance1":{
            "application": "/guest/hello-c",
            "distribution": "Poisson",
            "rate": 25,
            "activity_window": [5,10]
        }
   },
   "perf_monitoring":{
        "runtime_script": null,
        "post_script": null
    }
}
I use the above workload_configs.json. The language that I am using is C. I run ./WorkloadInvoker -c workload_configs.json and then I run ./WorkloadAnalyzer -r -p and I get the following messages. Can you help?
![test](https://user-images.githubusercontent.com/70962888/158261528-f7cd267f-a3af-4e0a-8b25-8af11e4d714f.PNG)

**Comment by engshahrad** [comment]
Is the`db_local.ini` file properly set for OpenWhisk? You can find more about this file and how to set it up here: https://github.com/apache/openwhisk/blob/master/tools/db/README.md

**Comment by engshahrad** [comment]
Closing the issue as there was no response/further questions in three weeks.
