### ISSUE TITLE
Verifying support for Python 3.10

### ISSUE THREAD

**Issue by engshahrad** [PrincetonUniversity/faas-profiler#16]
[Joe Hattori](https://github.com/joehattori) has reported to me difficulties with invoking functions on Python 3.10. The issue seems to be with the `requests` library. I need to investigate this.

**Comment by Nalin28** [comment]
I used faas-profiler to send traffic to Knative (endpoint: generic) I got it working by downgrading python from 3.10 to 3.8:

### Steps to reproduce:
- use the `workload_configs_generic_endpoint.json` under faas-profiler and specify your host and url (I used it with `interarrivals_list`). 
- run `$ ./WorkloadInvoker -c workload_configs_generic_endpoint.json`

### Error:
<img width="1173" alt="Screenshot 2023-08-06 at 5 44 02 PM" src="https://github.com/PrincetonUniversity/faas-profiler/assets/36547560/7d502592-d4e4-44af-9cd3-b871bf4796f1">

### Fix:
Downgrading Python to 3.8 (3.8.17 for me) and then retry.
