### ISSUE TITLE
Making `max_workers` a configurable parameter in the workload config JSON

### ISSUE THREAD

**Issue by Nalin28** [PrincetonUniversity/faas-profiler#23]
I used faas-profiler to send traffic to Knative (endpoint: generic) and it only sends in 100 async request invocations even though my workload config JSON has an ideal peak average concurrency of more than 100.

### Steps to reproduce:
Use the `workload_configs_generic_endpoint.json` under faas-profiler and specify your host and URL (I used it with interarrivals_list with average peak concurrency > 100). 
run `$ ./WorkloadInvoker -c workload_configs_generic_endpoint.json`

### Fix
Pass the field in the JSON as `max_worker` and propagate it through the WorkloadInvoker instead of hardcoding it.

**Comment by engshahrad** [comment]
#32 also resolves this.
