### ISSUE TITLE
Does this work on OpenWhisk setup on a kind cluster ?

### ISSUE THREAD

**Issue by Prithvi-Velicheti** [PrincetonUniversity/faas-profiler#28]

**Comment by engshahrad** [comment]
Haven't tested it there. May or may not work. If you end up testing it, it'd be great if you could share the outcome here.

**Comment by engshahrad** [comment]
The version we used in our MICRO '19 paper is stated in the paper: _"We use the public OpenWhisk source code, as released on GitHub1 and built from Git commit **084e5d3**."_ It was deployed on baremetal VMs.

I see researchers use FaaSProfiler for two different purposes:
- Traffic generation (synthetic or trace based) -> This one I know has been done in the context of Knative and OW on kubernetes. If you want to use it for this purpose, you're all good. 
- Detailed profiling -> This one I don't know whether any code change is needed to get it to work on systems named above, and if so how much. I'd assume it should not be that hard to add support for, but I don't have the BW right now. Feel free to work on it and contribute to the project.

**Comment by Prithvi-Velicheti** [comment]
Dear Dr Shahrad,

  Thanks a lot for your kind reply. Apologies for my overlooking. I currently intend to use FaaS traffic generators with known Function code (synthetic). So i believe FaaS Profiler helps me, unlike Invitro which just uses trace. I hopefully will try to contribute in coming future, when I am in good shape.

Kind Regards,
Prithvi.

**Comment by Prithvi-Velicheti** [comment]
One dumb question. Lately I have been facing lot of problems with Openwhisk installation. Its getting easily installed in kind cluster with helm. But when I am trying install in Standalone mode ? or with Dockers ( using Ansible) there are lot of bugs. This also could be lot of outdated configurations, which are not supported.  To work with FaaSProfiler, in what way I should install ? standalone or with ansible ?

**Comment by engshahrad** [comment]
It shouldn't matter which way you install if all you need from FaaSProfiler is traffic generation. Deploy the OpenWhisk however you want. Then create your functions (actions). Then you'll have an endpoint for it. You can then use FaaSProfiler in the "generic" endpoint mode to just send invocations to that function. See [this README](https://github.com/PrincetonUniversity/faas-profiler/blob/master/README.md) to learn more about using the "generic" endpoint.

**Comment by Prithvi-Velicheti** [comment]
thank you very much !

**Comment by engshahrad** [comment]
Closing this issue, as it's not an issue to be fixed, but more of a question. Please feel free to follow up if you have any questions, Prithvi.

**Comment by Prithvi-Velicheti** [comment]
Greetings ! thank you for your response.
