### ISSUE TITLE
custom Pintool

### ISSUE THREAD

**Issue by navdeepkk** [PrincetonUniversity/faas-profiler#4]
To study the branch prediction behaviour, you have used a "custom pintool" to  generate branch traces. I wanted to genrate these traces and wanted to observe their behaviour on 1-level branch predictors as they have lower warm-up times. Can you please give me the access to the tool or the traces?
Thank you

**Comment by engshahrad** [comment]
@Jbalkind , could you please guide Navdeep on this?

**Comment by navdeepkk** [comment]
@Jbalkind @engshahrad It would be really helpful if i could get the traces.

**Comment by Jbalkind** [comment]
Hi there,
The trace tool is not part of the FaaSProfiler release. I have now had a chance to look into the copyright restrictions around the code I reused and unfortunately we won't be able to open this up. As it's not part of FaaSProfiler, please get in touch directly by email if you'd like to discuss this more.
Thanks,
Jon
