### ISSUE TITLE
WorkloadAnalyzer Output Explanation

### ISSUE THREAD

**Issue by kkaffes** [PrincetonUniversity/faas-profiler#5]
Could you explain what exactly each column in WorkloadAnalyzer's output represents? More specifically:
* duration
* waitTime
* initTime
* latency
* invocation period

Thank you in advance.

**Comment by engshahrad** [comment]
Thanks for reaching out. 

Duration, wiatTime, and initTime are OpenWhisk parameters. You can find their definitions here: 
https://cloud.ibm.com/docs/openwhisk?topic=cloud-functions-monitor

We have defined latency as sum of waitTime (queuing time) and duration (execution). In other words, it's the total latency induced inside the Invoker. 
The invocation period output refers to the average inter-arrival time. [I think it's better to rename it for clarity.]

**Comment by kkaffes** [comment]
Thank you for your swift reply!

From the IBM website it is not entirely clear that the waitTime refers exclusively to the Invoker.

>  wait-time: The average time that is spent in a queue, waiting for an activation to be scheduled.

Are you sure that's the case?

Furthermore, is there any way to measure the end-to-end latency, or at least include the Controller-induced latency, using FaasProfiler?

**Comment by engshahrad** [comment]
My pleasure. :) 

Here, you can find a more detailed description of waitTime: 
https://github.com/apache/openwhisk/blob/master/docs/annotations.md

Note that the FaaSProfiler reads the initTime, duration, and waitTime recorded by the OpenWhisk. It does not define or in anyway modify these parameters.

Regarding the end-to-end latency, I think a reasonable approach is to track invocation request timestamp and request response timestamps. This is currently not done by FaaSProfiler, but should be fairly straightforward to add. 

An alternative approach is to read the event logs that are stored within OpenWhisk module containers (e.g., nginx, controller, etc.).

**Comment by kkaffes** [comment]
From the link you sent it seems that the wait-time includes the Controller-induced latency as well. I also noticed that you don't include the init-time in the latency calculation. Is it included in the wait-time? 

If I add end-to-end latency tracking, would you be interested in upstreaming it?

Thanks again!

**Comment by engshahrad** [comment]
Sorry, currently I'm not 100% sure about whether wait-time includes init-time (my hunch is that it doesn't, given the test results in Fig. 5 of our paper: http://parallel.princeton.edu/papers/micro19-shahrad.pdf). It would be best to look at the latest OpenWhisk code to check that.  

Yes, that's a great idea. I'd be interested in upstreaming the end-to-end latency tracking. You can also reach out to me by email if you wanted to discuss details regarding adding this feature. 

Thanks.
