### ISSUE TITLE
Monitoring Invokers

### ISSUE THREAD

**Issue by kkaffes** [PrincetonUniversity/faas-profiler#6]
In the current implementation, the monitoring scripts can only run in the server that runs faas profiler. How do you recommend adding support for running the monitoring scripts on the invoker nodes?

**Comment by engshahrad** [comment]
That is correct, the current methodology only allows running profiling scripts on the head node. I think (and honestly have been thinking that) it'd be great to add the distributed monitoring feature. As this is a great direction for next versions of FaaSProfiler, let us (and the community) discuss and find the best solutions. 

Part of the challenge is that there are different ways to deploy distributed OpenWhisk. For instance, one could have a distributed setup on multiple VMs, or on top of Kubernetes. The optimal solution looks different for these. 

Another way is to implement a performance measurement plugin within the invoker source (to try to make it as technology agnostic as much as possible). But that would limit the flexibility. Current methodology of running any script has unlimited flexibility, as one can include the desired tools in a single line. 

What are your thoughts?

**Comment by kkaffes** [comment]
The easiest way that comes to mind is to specify a list of nodes in the configuration file. The invocation script will assume passwordless ssh access and run the monitoring script(s) on all of them.

**Comment by engshahrad** [comment]
This seems feasible to implement using the already-available **ansible** for OpenWhisk (even password is no issue, as one can ssh into nodes). There would be a small catch though. Given that the performance measurement on each node would be timestamped with local time, one should be careful to use execution time starts locally. This would be necessary to eliminate the timing jitters across nodes.
